spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties:
    hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-54-173-237-110.compute-1.amazonaws.com/daskp4lqgg1h9p
  username: ysiykojdrhobhs
  password: 2b822726fe0e6ace7991487a498b287ba3d244f1d8add54cbae872a36dca2fbb
  driver-class-name: org.postgresql.Driver

spring:
  thymeleaf3.decoupled-logic: true

jwt:
  secret-key: springboot_it_study_community_2022.secret_key
  # 30 days 24*60*60*30
  token.expired-time-ms: 2592000000
