spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties:
    hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-34-227-135-211.compute-1.amazonaws.com/dc17li9ac25m5t
  username: pdijyvreepmauu
  password: c5052b72fd5c4260deb96c377c61955dae11852c80a6c7685cafa19cd0e83a66
  driver-class-name: org.postgresql.Driver

spring:
  thymeleaf3.decoupled-logic: true

jwt:
  secret-key: springboot_it_study_community_2022.secret_key
  # 30 days 24*60*60*30
  token.expired-time-ms: 2592000000
