spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties:
    hibernate.format_sql: true
  show-sql: true

spring:
  thymeleaf3.decoupled-logic: true
